[workspace]

members = [
    "components/cldr-json-data-provider",
    "components/data-provider",
    "components/fs-data-provider",
    "components/icu",
    "components/icu4x",
    "components/uniset",
    "components/locale",
    "components/num-util",
<<<<<<< HEAD
    "components/pluralrules",
=======
>>>>>>> 9096b5d... adds other components as GH bench action param vals; remove experimental test drivers component for benches
]
