# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/master/LICENSE ).
[config]
default_to_workspace = false
load_cargo_aliases = true

### INDIVIDUAL TEST AND LINT TASKS ###
# Note: If a task is purely a cargo alias, define it in .cargo/config.toml

[tasks.build-all-features]
description = "Build all permutations of all features"
category = "ICU4X Development"
install_crate = { crate_name = "cargo-all-features", binary = "cargo-build-all-features", test_arg = ["--help"] }
install_crate_args = ["--version", "^1.4"]
command = "cargo"
args = ["build-all-features"]

[tasks.license-header-check]
description = "Ensure all the source files have license headers"
category = "ICU4X Development"
script_runner = "@duckscript"
script = '''
exit_on_error true
handle = glob_array ./**/*.rs

for path in ${handle}
    text = readfile ${path}
    result = starts_with ${text} "// This file is part of ICU4X. For terms of use, please see the file"
    if not ${result}
        echo "License header missing in ${path}"
        trigger_error "License header missing in ${path}"
    end
end

handle = glob_array ./**/*.yml

for path in ${handle}
    text = readfile ${path}
    result = starts_with ${text} "# This file is part of ICU4X. For terms of use, please see the file"
    if not ${result}
        echo "License header missing in ${path}"
        trigger_error "License header missing in ${path}"
    end
end


handle = glob_array ./**/*.toml

for path in ${handle}
    text = readfile ${path}
    result = starts_with ${text} "# This file is part of ICU4X. For terms of use, please see the file"
    if not ${result}
        echo "License header missing in ${path}"
        trigger_error "License header missing in ${path}"
    end
end
'''

### META TASKS ###

[tasks.quick]
description = "Run quick version of all lints and tests"
category = "ICU4X Development"
dependencies = [
    "test-all",
    "fmt-check",
    "clippy-all",
]

[tasks.ci]
description = "Run all lints and tests"
category = "ICU4X Development"
dependencies = [
    "quick",
    "test-docs",
    "build-all-features",
    "license-header-check",
]
