[package]
name = "icu-num-util"
description = "Low-level tools for dealing with numbers"
version = "0.0.1"
authors = ["The ICU4X Project Developers"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/unicode-org/icu4x"
license-file = "../../LICENSE"
categories = ["internationalization"]
include = [
    "src/**/*",
    "Cargo.toml",
    "README.md"
]

[dependencies]
smallvec = "1.4.0"
num-traits = "0.2.12"
num-integer = "0.1.43"
static_assertions = "1.1.0"
more-asserts = "0.2.1"

[dev-dependencies]
rand = "0.7.3"
criterion = "0.3"
num-bigint = "0.3"
rand_pcg = "0.2.1"
rand_distr = "0.2.2"

[[bench]]
name = "isize"
harness = false
