name: Perf - Runtime

on:
  push:
    branches: [ master ]
  pull_request:
    branches: '*'

jobs:
  benchmark:
    strategy:
      fail-fast: false
      # `matrix` creates a job matrix (Cartesian product of possible values for each var)
      # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix
      matrix:
        component:
          - locale
          - num-util
          - uniset
      # Ensure that commits when pushing GH pages to external has linear commit
      # history w/o merges (to keep things simpler). Do this via max-parallel=1
      max-parallel: 1

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Try on a particular component
        run: cd components/${{ matrix.component }}

      - name: Run benchmark
        run: cd components/${{ matrix.component }} && (cargo bench -- --output-format bencher | tee output.txt) && cd ../..

      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1.8.1
        with:
          name: Rust Benchmark
          tool: 'cargo'
          output-file-path: components/${{ matrix.component }}/output.txt
          # Use personal access token instead of GITHUB_TOKEN due to https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/td-p/26869/highlight/false
          # Not using this action to push GH pages, so using GITHUB_TOKEN b/c it is just for commenting on the commit on alert
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@sffc @zbraniecki @echeran'
          gh-pages-branch: gh-pages-${{ matrix.component }}

      - name: Dashboard -> Github Pages
        uses: peaceiris/actions-gh-pages@v3.7.0-6
        ## Only create docs for merges/pushes to master (skip PRs).
        ## Multiple unfinished PRs should not clobber docs from approved code.
#        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          # Setup for publishing to an external repo using `deploy_key` option:
          #
          # Step 1 - Create SSH key pair. Use your public key as a Github "Deploy Key" and your private
          # key as a Github "Secret". Where to register these keys comes next.
          # https://github.com/marketplace/actions/github-pages-action#%EF%B8%8F-create-ssh-deploy-key
          #
          # Step 2 - After creating public/private key pair, put the private key in the repo running the
          # action as a Secret and call it "ACTIONS_DEPLOY_KEY". Put the public key as a Deploy Key in the
          # target repo where the Github Pages will be copied to.
          # https://github.com/marketplace/actions/github-pages-action#%EF%B8%8F-deploy-to-external-repository
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
#          external_repository: unicode-org/icu4x-docs
          external_repository: echeran/icu4x-docs
          publish_branch: gh-pages-${{ matrix.component }}
          publish_dir: ./dev/bench
          destination_dir: dev/${{ matrix.component }}/bench
          commit_message: Benchmark Dashboard -> GH Pages
